### ISSUE TITLE
 ǖ ǘ ǚ ǜ ü are not u, they are v

### ISSUE THREAD

**Issue by DogLooksGood** [Anoncheg1/pinyin-isearch#1]
As the title says, `v` is used to represent `ü` and these two representations are not interchangeable. e.g. `lu`/`lv` and `nu/nv`.

**Comment by Anoncheg1** [comment]
I get rid of "v" completely, In new version v0.4. 
Now only "u" is used for [ūúǔùǖǘǚǜ]
Is it good or: ūúǔù and ǖǘǚǜ should be separated?

look at (pinyin--prepare-query ...) in pinyin-isearch-tests.el file, plz.

**Comment by DogLooksGood** [comment]
Well, `u` and `ü` are different vowels with different pronunciations.

**Comment by Anoncheg1** [comment]
kuà, Quán as well as nǚ found well with simple: kua, quan, nu.

**Comment by DogLooksGood** [comment]
`nǚ` is `nv`, its pronunciation is `/ny/`, example characters: 女
`nǔ` is `nu`, its pronunciation is `/nu/`, example characters: 努，弩
